export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const DOWNLOAD_PRODCUTS =  'DOWNLOAD_PRODCUTS';
export const DOWNLOAD_PRODCUTS_SUCCESS =  'DDOWNLOAD_PRODCUTS_SUCCES';
export const DOWNLOAD_PRODCUTS_ERROR =  'DOWNLOAD_PRODCUTS_ERROR';

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR';

export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT';
export const START_EDIT_PRODUCT = 'START_EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';